name: Goseek

services:
  goseek-dev:
    profiles: ["goseek-dev"]
    image: goseek:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: goseek_dev
    container_name: goseek-dev
    environment:
      - GIN_MODE=debug
    networks:
      - goseek_network
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "8080:8080"

  goseek-stage:
    profiles: ["goseek-stage"]
    image: goseek:stage
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: goseek_stage
    container_name: goseek-stage
    environment:
      - GIN_MODE=release
    networks:
      - goseek_network
    ports:
      - "8080:8080"

  goseek-prod:
    profiles: ["goseek-prod"]
    image: goseek:prod
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: goseek_prod
    container_name: goseek-prod
    environment:
      - GIN_MODE=release
    networks:
      - goseek_network
    ports:
      - "8080:8080"

networks:
  goseek_network:
    driver: bridge
